export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADDTO_CART: "ADDTO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    ADJUST_QTY: "ADJUST_QTY",
};